### ISSUE TITLE
Please document Programmatic Usage

### ISSUE THREAD

**Issue by vanthome** [tsamaya/random-points-generator#1]
Hi,

thx for the lib! can you also document how to use it programmatically?

what is the difference to this one:
https://github.com/mapbox/geojson-random

?

**Comment by tsamaya** [comment]
Hi,
Thank you for the question.
I did this lib because I needed to generate points within a shape. That is the main difference with the mapbox one, where only bounding box filter is available. 
I also used it only via the node command line and not really take time to document the usage on other lib.
Regards
